server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_verify_app
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true